- Cargo.lock
- Cargo.toml
- py-kornia/Cargo.lock
- src/io/functional.rs
- add the crate `memmap2` to read images directly from memory
- fixes #40
> use memmap2 to read images and fixes

- src/warp/affine.rs
- src/warp/mod.rs
- src/warp/perspective.rs
- make `warp` as submodule
- create `warp_perspective` as public function
> implement warp_perspective

- examples/undistort_image.rs
- src/calibration/distortion.rs
- src/calibration/mod.rs
- src/image.rs
- src/interpolation/grid.rs
- src/interpolation/mod.rs
- src/lib.rs
- src/resize.rs
- src/warp/affine.rs
- src/warp/perspective.rs
> implement image undistortion

- Cargo.lock
- Cargo.toml
- src/tensor/allocator.rs
- src/tensor/base.rs
- src/tensor/mod.rs
- src/tensor/serde.rs
- src/tensor/storage.rs
- implement `TensorStorage` and `TensorAllocator`
- the `TensorStorage` is implemented in terms of `arrow::buffer::Buffer` https://docs.rs/arrow/latest/arrow/buffer/struct.Buffer.html
> Implement Tensor Memory allocator

- src/enhance.rs
- src/lib.rs
> feat: enhance add weighted

- Cargo.toml
- examples/webcam/Cargo.toml
- examples/webcam/src/main.rs
- src/io/webcam.rs
- handle gracefully webcam errors with `StreamCaptureError`
- simplify webcam example
> handle gracefulle webcam / gstreamer errors

- crates/kornia-core/src/storage.rs
- crates/kornia-image/src/image.rs
- crates/kornia-imgproc/Cargo.toml
- crates/kornia-imgproc/benches/bench_color.rs
- crates/kornia-imgproc/benches/bench_metrics.rs
- crates/kornia-imgproc/benches/bench_resize.rs
- crates/kornia-imgproc/benches/bench_warp.rs
- crates/kornia-imgproc/src/color/gray.rs
- crates/kornia-imgproc/src/threshold.rs
- crates/kornia-io/benches/bench_io.rs
- improve benchmarks [index.zip](https://github.com/user-attachments/files/16824807/index.zip)
> Improve Rust benchmarks

- crates/kornia-core/src/storage.rs
- crates/kornia-imgproc/benches/bench_metrics.rs
- crates/kornia-imgproc/benches/bench_resize.rs
- crates/kornia-imgproc/benches/bench_warp.rs
- crates/kornia-io/src/stream/camera.rs
- crates/kornia-io/src/stream/capture.rs
- crates/kornia-io/src/stream/rtsp.rs
- examples/rtspcam/src/main.rs
- examples/webcam/src/main.rs
- fixes #120 
- fixes #119
- introduce `run_with_termination`
- improve benches with `black_box` only in constants
> Close streamer with termination and other stability fixes

- crates/kornia-core/src/tensor.rs
> Tensor get bounds check

- crates/kornia-imgproc/src/core.rs
implement `kornia_imgproc::core::hconcat` to stack images horizontaly
> implement hconcat operator

- crates/kornia-imgproc/src/draw.rs
- crates/kornia-imgproc/src/lib.rs
- implement `kornia_imgproc::draw::draw_line`
- for now support basic line drawing in place
> implement `draw_line` in `kornia-improc`

- examples/onnx/Cargo.toml
> pin ort and ort-sys to v2.0.0.rc8 and add half feature

- Cargo.toml
- crates/kornia-io/src/fps_counter.rs
- examples/color_detector/Cargo.toml
- examples/hello_world/Cargo.toml
- examples/histogram/Cargo.toml
- examples/imgproc/Cargo.toml
- examples/metrics/Cargo.toml
- examples/normalize/Cargo.toml
- examples/normalize_ii/Cargo.toml
- examples/onnx/Cargo.toml
- examples/onnx/src/main.rs
- examples/rerun_viz/Cargo.toml
- examples/rotate/Cargo.toml
- examples/rtspcam/Cargo.toml
- examples/rtspcam/src/main.rs
- examples/std_mean/Cargo.toml
- examples/undistort_image/Cargo.toml
- examples/video_write tasks/Cargo.toml
- examples/video_write/Cargo.toml
- examples/webcam/Cargo.toml
- examples/webcam/src/main.rs
- kornia-viz/Cargo.toml
- kornia-viz/README.md
- kornia-viz/src/bin/app.rs
- kornia-viz/src/keyboard_state.rs
- kornia-viz/src/lib.rs
- add crate kornia-viz as an experiment with `egui` for future projects
- update rerun to `^0.20` in the examples
- update `FpsCounter` to support continuous updates
> Add experimental Kornia viz

- crates/kornia-imgproc/src/filter/separable_filter.rs
fixes regression introduced in eea28ac98073c1ced33eb3f24632dad3ebe8fc80
This pull request includes several optimizations and improvements to the `separable_filter` function in the `crates/kornia-imgproc/src/filter/separable_filter.rs` file. The changes primarily focus on improving buffer allocation strategies and optimizing pixel access methods.
Optimizations to buffer allocation and pixel access:
* Added a TODO comment to improve the buffer allocation strategy for the temporary buffer used for intermediate results.
* Simplified the calculation of `x_pos` and improved the pixel access method by removing unnecessary bounds checks and using `unsafe` for direct memory access.
* Simplified the calculation of `y_pos` and improved the pixel access method by removing unnecessary bounds checks …
> fix `separable_filter` regression

- Cargo.toml
- crates/kornia-3d/Cargo.toml
- crates/kornia-icp/Cargo.toml
- kornia-py/Cargo.toml
- scripts/release_rust.sh
This pull request includes several updates to the `Cargo.toml` files of various crates and a script adjustment to improve the release process.
Version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L23-R34): Updated the version of the main package and its dependencies from `0.1.8-rc.1` to `0.1.8`.
* [`kornia-py/Cargo.toml`](diffhunk://#diff-b578890f0af57d109322f0341862126b0c113a3203c7fbcedf2a7d9bf1308fd2L11-R11): Updated the version from `0.1.8-rc.1` to `0.1.8`.
Publishing configuration:
* [`crates/kornia-3d/Cargo.toml`](diffhunk://#diff-ec56b78c19427d2248c2b703d2b8579e21de7180802f42a564039b57cf8621efL8-R9): Added `publish = true` to enable publishing of the crate.
* [`crates/kornia-icp/Cargo.toml`](diffhunk://#diff-9de0a38a4ce47e …
> Release 0.1.8

- Cargo.toml
- README.md
- crates/kornia-3d/Cargo.toml
- crates/kornia-3d/src/io/colmap/text.rs
- crates/kornia-3d/src/io/colmap/types.rs
- crates/kornia-3d/src/io/mod.rs
- crates/kornia-3d/src/io/pcd/parser.rs
- crates/kornia-3d/src/io/ply/mod.rs
- crates/kornia-3d/src/io/ply/parser.rs
- crates/kornia-3d/src/io/ply/properties.rs
- crates/kornia-3d/src/lib.rs
- crates/kornia-3d/src/pose/homography.rs
- crates/kornia-3d/src/vector.rs
- crates/kornia-icp/Cargo.toml
- crates/kornia-icp/src/lib.rs
- crates/kornia-image/Cargo.toml
- crates/kornia-image/src/lib.rs
- crates/kornia-imgproc/Cargo.toml
- crates/kornia-imgproc/src/filter/kernels.rs
- crates/kornia-imgproc/src/lib.rs
- crates/kornia-io/src/lib.rs
- crates/kornia-tensor-ops/Cargo.toml
- crates/kornia-tensor-ops/src/lib.rs
- crates/kornia-tensor/Cargo.toml
- crates/kornia-tensor/src/lib.rs
- crates/kornia/Cargo.toml
- crates/kornia/src/lib.rs
- examples/onnx/Cargo.toml
- examples/onnx/src/main.rs
- scripts/release_rust.sh
This pull request includes various changes to improve documentation, add descriptions to several modules, and include new dependencies. The most important changes include adding missing documentation, updating descriptions in `Cargo.toml` files, and adding new dependencies to the `README.md`.
Documentation improvements:
* [`crates/kornia-3d/src/io/colmap/text.rs`](diffhunk://#diff-45d911ff4f359d3accb568b95627ee1cf84e9b342c67450a1f04a95d7f8afe2bR9-R20): Added documentation comments to `ColmapError` enum variants.
* [`crates/kornia-3d/src/io/colmap/types.rs`](diffhunk://#diff-541646ec3888a041f2b3ea41403267a95c853708ba8466b3207f63d445452809R3-R83): Added documentation comments to `Vector2d`, `CameraModelId`, `ColmapCamera`, `ColmapImage`, and `ColmapPoint3d` structs.
* …
> chore: fix readme docs in top level kornia package

- crates/kernels/benches/bench_kernels.rs
- crates/kornia-3d/src/io/ply/properties.rs
- crates/kornia-imgproc/src/features.rs
- crates/kornia-linalg/Cargo.toml
- crates/kornia-linalg/src/linalg.rs
- justfile
fixes from https://github.com/kornia/kornia-rs/pull/241
> chore: fix clippy and check errors

- crates/kornia-tensor-ops/benches/bench_ops.rs
- crates/kornia-tensor-ops/src/ops.rs
fixes from https://github.com/kornia/kornia-rs/pull/272
> tensops: fix self reference for internal methods

- crates/kornia-imgproc/Cargo.toml
- crates/kornia-imgproc/benches/bench_pyramid.rs
- crates/kornia-imgproc/src/lib.rs
- crates/kornia-imgproc/src/pyramid.rs
This issue aims to resolve #249. I have implemented pyrup using only resize_native and removed the function using resize_fast.
Further suggestions are welcome.
> Implemented Pyrup

- crates/kornia-image/src/image.rs
> Implement image map

- .github/workflows/python_test.yml
- kornia-py/Cargo.toml
See https://github.com/kornia/kornia-rs/issues/226#issuecomment-2749385053 for more context.
> Update python bindings to be compatible with free-threading, add CI

- Cargo.toml
- crates/kornia-io/src/functional.rs
- crates/kornia-io/src/jpegturbo.rs
- kornia-py/src/io/functional.rs
- kornia-py/src/io/jpeg.rs
> python: improve encoders mutability

- .github/workflows/python_test.yml
- README.md
- kornia-py/src/lib.rs
See https://github.com/kornia/kornia-rs/issues/226, in particular https://github.com/kornia/kornia-rs/issues/226#issuecomment-2766664990.
> declare support for the free-threaded build

- crates/kornia-image/src/error.rs
- crates/kornia-io/Cargo.toml
- crates/kornia-io/src/error.rs
- crates/kornia-io/src/jpeg.rs
- crates/kornia-io/src/jpegturbo.rs
- crates/kornia-io/src/lib.rs
- crates/kornia-io/src/png.rs
- crates/kornia-tensor/src/tensor.rs
- kornia-py/src/color.rs
- kornia-py/src/image.rs
- kornia-py/src/io/functional.rs
- kornia-py/src/io/jpeg.rs
- kornia-py/src/io/mod.rs
- kornia-py/src/io/png.rs
- kornia-py/src/io/turbojpeg.rs
- kornia-py/src/lib.rs
- kornia-py/tests/test_io.py
Fixes #121 
This PR also improves error message of `IoError`
I created this PR even #270 exists because of [Discord Message](https://discord.com/channels/1295102166763049061/1319987694377635840/1355800511466700960), and also that PR uses some types of jpegturbo that doesn't exists
This PR will be conflicted once #334 merges, I will rebase and fix the conflicts once it is merged. _**Rebased**_
> Decode Images directly from raw bytes

- kornia-py/src/icp.rs
- kornia-py/src/image.rs
> Add frozen attribute to Python wrapper classes

- crates/kornia-lie/src/se2.rs
- crates/kornia-lie/src/se3.rs
- crates/kornia-lie/src/so2.rs
- crates/kornia-lie/src/so3.rs
- fix wrong column major access members
- relax tests for aarch64 with higher epsilon
> lie: fix col major issues and relax aarch64 epsilon tests

- .github/workflows/rust_lint.yml
- .github/workflows/rust_test.yml
- crates/kornia-vlm/Cargo.toml
- crates/kornia-vlm/src/lib.rs
- crates/kornia-vlm/src/paligemma/mod.rs
- crates/kornia-vlm/src/paligemma/model.rs
- crates/kornia-vlm/src/paligemma/utils.rs
import paligemma from https://github.com/kornia/kornia-paligemma
> vlm: implement paligemma using candle

- crates/kornia-3d/Cargo.toml
- crates/kornia-3d/src/io/pcd/parser.rs
- crates/kornia-3d/src/io/ply/mod.rs
- crates/kornia-3d/src/io/ply/properties.rs
- crates/kornia-apriltag/src/iter.rs
- crates/kornia-lie/src/se2.rs
- examples/rtspcam/src/main.rs
fixes #399 
- update bincode to use from workspace in kornia-3d crate
- fix clipy complaints
> use bincode from workspace for loading pointclouds

- crates/kornia-lie/src/se2.rs
- examples/paligemma/Cargo.toml
- examples/paligemma/README.md
- examples/paligemma/src/main.rs
import the paligemma example from https://github.com/kornia/kornia-paligemma/blob/main/examples/inference.rs
> create paligemma example

- crates/kornia-lie/src/se2.rs
- crates/kornia-lie/src/se3.rs
- crates/kornia-lie/src/so2.rs
- crates/kornia-lie/src/so3.rs
This PR adds plus and minus operators for Lie groups
> feat: add rplus,rminus,lplus,lminus for lie groups

- crates/kornia-apriltag/src/family.rs
- crates/kornia-apriltag/src/lib.rs
- crates/kornia-apriltag/src/quad.rs
- crates/kornia-apriltag/src/segmentation.rs
- crates/kornia-apriltag/src/utils.rs
> Add Quad Fitting

- examples/apriltag/Cargo.toml
- examples/apriltag/README.md
- examples/apriltag/src/main.rs
> Add AprilTag detection example

- .gitmodules
I have transferred the ownership of apriltag-imgs from my personal account to kornia
> Update `apriltag-imgs` submodule URL
