kornia/kornia-rs

.github/workflows/release.yml
Reimplementation for  release.yml 
Signed-off-by: carlosb1 <mcflurry0@gmail.com>
=> Workflow reimplementation

README.md
As communicated on slack, I added installation instruction to README, specifically for install from source. This will help users when their binary wheels are not available on PyPI e.g. MacOS ARM64 Python3.10+.
Let me know if you want any modifications @edgarriba
=> Add installation instruction to README

.github/workflows/release.yml
As communicated on Slack, I added workflow to build MacOS ARM64 binaries to support Apple Silicon. I downloaded the wheels and tested on my local M1. Installation worked fine and all pytest tests passed. I only tested Python 3.8-3.11, since there is no Python 3.7 MacOS ARM64 from conda. (I think no one builds Python 3.7 for MacOS ARM64? Anyway, Python 3.7 is reaching end-of-life this June so perhaps we can even stop building for Python 3.7).
This is the workflow run in my fork: https://github.com/gau-nernst/kornia-rs/actions/runs/4263731867
The Linux builds are failing because I don't have access to the Docker images.
Also, this closes #20
=> Build MacOS ARM64 binaries with GHA

.github/workflows/python_release.yml, .github/workflows/python_test.yml, .github/workflows/rust_test.yml, Cross.toml, devel-i686.Dockerfile, py-kornia/Cargo.lock, py-kornia/Cargo.toml, py-kornia/pyproject.toml
- release python 3.12
- add macos python test in ci
- add linux i686 in ci
- deprecate dlpack-rs for now
=> ci improvements

Cargo.toml, benches/metrics_benchmark.rs, examples/binarize.rs, examples/imgproc.rs, examples/metrics.rs, src/flip.rs, src/image.rs, src/lib.rs, src/metrics/huber.rs, src/metrics/l1.rs, src/metrics/mod.rs, src/metrics/mse.rs
- add the kornia_rs::metrics module
- implement metrics: mse, l1_loss, psnr, huber
- implement image builtins: sub, powi, mean, abs
- fixes implementation of horizontal flip
- add metrics bench and example
=> add kornia_rs::metrics

.github/workflows/python_test.yml, .gitignore, Cargo.toml, examples/binarize.rs, examples/histogram.rs, examples/imgproc.rs, examples/metrics.rs, examples/rerun_viz.rs, kornia-py/benchmark/bench_io.py, kornia-py/src/image.rs, src/image.rs
- add `.to_tensor_nchw()` and `.to_tensor_nhwc()` to the `Image` struct to easily convert images e.g to feed to onnxruntime
- make `Image.data()` pub (crate) to avoid leaks from user perspective
- some tweaks in the rerun examples logs api
=> add Image to tensor built in utils

src/resize.rs
This is my prototype to support resize with different dtypes. Justifications for trait
- `Copy` trait: to get the value out of `ndarray::Array<T, _>`
- `Default` trait: to get 0 value
- `Into<f32>` trait: to convert to f32 for internal computation i.e. bilinear/bicubic
- `Send` and `Sync` trait: required for `ndarray::Zip::par_for_each()`
- `from_f32()` function: convert from internal computation dtype f32 back to original dtype. We can't use `From<f32>` since it is undefined-behavior with underflow and overflow values i.e. we need to clamp the value by ourselves.
I think `ImageDtype` trait can be moved to `image.rs` and data within `Image` must implement `ImageDtype` trait i.e. these are the dtype that we support -> `pub struct Image<T: ImageDtype, const CHANNELS: usize>`
=> [prototype] `ImageDtype` trait to implement resize for various dtypes

examples/rotate.rs
https://github.com/kornia/kornia-rs/assets/5157099/59cb8fef-0e5c-4cd8-b502-a1fbae0c4af2
=> add rotate example

README.md, crates/kornia-image/src/image.rs, crates/kornia-image/src/lib.rs, crates/kornia-imgproc/benches/bench_resize.rs, crates/kornia-imgproc/src/resize.rs, crates/kornia-imgproc/src/warp/perspective.rs, examples/imgproc/src/main.rs, examples/normalize_ii/src/main.rs, examples/rtspcam/src/main.rs, examples/webcam/src/main.rs, kornia-py/src/resize.rs
- remove `new_size` from `resize_native` / `resize_fast` and infer from dst image
- implement `cast_and_scale` into `image` module to receive mutable images
=> remove new_size and implement cast_and_scale

crates/kornia-core/Cargo.toml, crates/kornia-core/src/lib.rs, crates/kornia-core/src/serde.rs, crates/kornia-core/src/storage.rs, crates/kornia-core/src/tensor.rs
- implement `SafeTensorType` to support tuple structs out of Tensor
- bump  arrow-buffer to 52.2.0
- use strongly typed `arrow::ScalarBuffer<T>` over `arrow::Buffer`
- https://docs.rs/arrow-buffer/latest/arrow_buffer/buffer/struct.ScalarBuffer.html
- make data buffer private in TensorStorage
- expose `len()` / `is_empty()` / `as_slice()` / `as_mut_slice()` in storage
=> TensorStorage improvements

README.md, crates/kornia-imgproc/src/color/gray.rs, crates/kornia-io/benches/bench_io.rs, crates/kornia-io/src/functional.rs, kornia-py/src/io/functional.rs
This is common in other libraries and allows `Path`, `PathBuf`, `&str` and `String` to be passed into the function and automatically converted to a `Path`.
=> Simplify handling paths by using `impl AsRef<Path>` for JPEG functions

crates/kornia-core/Cargo.toml, crates/kornia-core/src/lib.rs, crates/kornia-core/src/storage.rs, crates/kornia-core/src/tensor.rs, crates/kornia-core/src/view.rs
- implement a `TensorView` struct to leverage axes permutations
- implement `as_ptr` /  `get` / `get_unchecked`  in `TensorStorage`
- expose `as_ptr` in `Tensor`
- return `TensorView` in `Tensor::reshape`
- implement `Tensor::permute_axes` and return `TensorView`
- implement `Tensor::view` to return `TensorView`
- `Tensor::get` now returns `Option` to align with Arrow and ndarray
- added some of tests
=> Implement TensorView

crates/kornia-core/src/storage.rs, crates/kornia-core/src/tensor.rs
- implement `Tensor` / `TensorStorage`  -- `into_vec()` to accomplish zero-copies between other libraries e.g `ort` @decahedron1
=> implement Tensor into_vec

crates/kornia-core/src/lib.rs, crates/kornia-core/src/tensor.rs, crates/kornia-core/src/view.rs
- implement `as_contiguous` in `TensorView` to assure contiguous memory
- add some `#[inline]` methods in `Tensor`
- add tests
=> implement tensorview as_contiguous

crates/kornia-core/Cargo.toml, crates/kornia-io/src/stream/capture.rs, examples/rtspcam/src/main.rs
- updates arrow-buffer to 53.0.0
- allow `StreamCapture::run_with_termination` to pass an awaitable closure
- update camera examples
=> support async closure in the stream camera

crates/kornia-imgproc/benches/bench_flip.rs, crates/kornia-io/Cargo.toml, crates/kornia-io/src/stream/capture.rs, crates/kornia-io/src/stream/error.rs, crates/kornia-io/src/stream/mod.rs, crates/kornia-io/src/stream/video.rs, examples/video_write tasks/Cargo.toml, examples/video_write tasks/README.md, examples/video_write tasks/src/main.rs, examples/video_write/Cargo.toml, examples/video_write/README.md, examples/video_write/src/main.rs
part of #113 
- create a `video.rs` in `kornia-io`
- implement `VideoWritter` and `VideoWriterCodec` to record h264/rgb videos
- added a new gstreamer error GstreamerFlowError and replaced DowncastAppSinkError by GetElementByNameError.
- create a couple of examples: `video_write` and `video_write_tasks`
- clippy fixes in the benchmarks
Output example:
https://github.com/user-attachments/assets/a51e01c5-4b4d-4209-89f8-ff7862fa251f
=> Implement H264 VideoWritter with gstreamer

crates/kornia-core/src/tensor.rs
=> Tensor display

crates/kornia-core/src/allocator.rs, crates/kornia-core/src/serde.rs, crates/kornia-core/src/storage.rs, crates/kornia-core/src/tensor.rs, crates/kornia-core/src/view.rs
**Changes in this PR**
- Adds checks to make sure the TensorAllocator is invoked properly.
- Fixes memory leaks/issues observed in https://github.com/kornia/kornia-rs/issues/134#issuecomment-2363726170 and https://github.com/kornia/kornia-rs/pull/117#issuecomment-2343983888.
**Details**
A new struct `TensorCustomAllocationOwner` is added to represent a custom memory allocations made by TensorAllocators. This struct implements the `Drop` trait to deallocate the associated memory. An instance of this struct is then passed as owner to `arrow_buffer::Buffer::from_custom_allocation`, so that when the Arrow buffer is dropped, this memory will also be deallocated using the correct TensorAllocator.
**Future changes**
When the `allocator_api` feature comes to stable rust, it may be possible to use …
=> Fix TensorStorage memory deallocation

crates/kornia-core/src/storage.rs, crates/kornia-core/src/tensor.rs, crates/kornia-image/src/image.rs
- use builtin `Buffer::from_slice_ref` in TensorStorage creation
- add method `from_size_slice` in `Image`
- implement `TryFrom` for Image/Tensor conversion
- added tests
=> improve image tensor conversions

Cargo.toml, crates/kornia-imgproc/src/color/gray.rs, crates/kornia-imgproc/src/color/mod.rs, crates/kornia-imgproc/src/enhance.rs, examples/onnx/Cargo.toml, kornia-py/Cargo.toml, kornia-py/src/color.rs, kornia-py/src/enhance.rs, kornia-py/src/image.rs, kornia-py/src/lib.rs, kornia-py/src/warp.rs, kornia-py/tests/test_color.py, kornia-py/tests/test_enhance.py, kornia-py/tests/test_warp.py
fixes #148 #112 
- implement `rgb_from_gray`, `bgr_from_rgb` in rust
- reorder signatures in `add_weighted` as i opencv
- expose to python `rgb_from_gray` , `bgr_from_rgb` , `gray_from_rgb` , `add_weighted` , `warp_perspective`
- add more python tests
=> Implement more `imgproc` functionality

crates/kornia-imgproc/Cargo.toml, crates/kornia-imgproc/benches/bench_crop.rs, crates/kornia-imgproc/src/crop.rs, crates/kornia-imgproc/src/lib.rs
- implement an image crop function in `kornia_improc::crop`
=> implement a crop function

Cargo.toml, crates/kornia-core-ops/Cargo.toml, crates/kornia-core-ops/src/error.rs, crates/kornia-core-ops/src/lib.rs, crates/kornia-core-ops/src/ops.rs, crates/kornia-core/src/allocator.rs, crates/kornia-core/src/tensor.rs, crates/kornia/Cargo.toml, crates/kornia/src/lib.rs
Separate the core tensor operations from the core crate to a core-ops crate.
=> create new crate for core-ops

README.md
Fixed #159 
Error when trying `Getting Started` command `cargo run --bin hello_world`
=> Getting started README Fix

.github/workflows/python_release.yml, kornia-py/Cargo.toml
- updates .github/workflows/python_release.yml to `actions/upload-artifact@v3`
- updates .github/workflows/python_release.yml to `actions/download-artifact@v3`
- do not inlcude `gstreamer` feature in kornia-py
=> Fix github python release

.github/workflows/python_release.yml, crates/kornia-imgproc/Cargo.toml, crates/kornia-io/src/jpeg.rs, kornia-py/Cargo.toml, kornia-py/src/image.rs, kornia-py/src/io/jpeg.rs
fixes #178 
This pull request includes several changes to the build and dependency management configurations, as well as modifications to the JPEG encoder and decoder implementations to improve thread safety. The most important changes are grouped into build configuration updates and codebase improvements.
* [`.github/workflows/python_release.yml`](diffhunk://#diff-ab7d347c52bff9333700f9be8b88adeec2d9663e0eb07728f36461d3c5b09e34L15-R15): Added Python 3.13 to the matrix for Ubuntu, macOS, and Windows builds. [[1]](diffhunk://#diff-ab7d347c52bff9333700f9be8b88adeec2d9663e0eb07728f36461d3c5b09e34L15-R15) [[2]](diffhunk://#diff-ab7d347c52bff9333700f9be8b88adeec2d9663e0eb07728f36461d3c5b09e34R74-R79) [[3]](diffhunk://#diff-ab7d347c52bff9333700f9be8b88adeec2d9663e0eb07728f36461d3c5b09e34L102-R11 …
=> support python 3.13

.github/workflows/python_test.yml, crates/kornia-3d/src/io/ply/mod.rs, crates/kornia-3d/src/io/ply/parser.rs, crates/kornia-3d/src/io/ply/properties.rs, examples/ply_rerun/README.md, examples/ply_rerun/src/main.rs
This pull request introduces significant enhancements to the PLY file handling in the `kornia-3d` crate, including support for additional PLY formats and refactoring of existing code to improve modularity and readability.
https://github.com/user-attachments/assets/56a9657f-e126-499e-a530-79897ffea88c
Key changes include:
* Added a new `PlyError` enum in `crates/kornia-3d/src/io/ply/mod.rs` for standardized error handling across PLY operations.
* Refactored the `PlyProperty` enum to `PlyType` and introduced the `PlyPropertyTrait` trait to handle different PLY property types more generically.
* Implemented the `PlyPropertyTrait` for `OpenSplatProperty` and `XYZRgbNormalsProperty` to convert properties to points, colors, and normals.
* Updated the `read_ply_binary` function to use the new …
=> implement XYZRgbNormalsProperty in ply parser

crates/kornia-imgproc/Cargo.toml, crates/kornia-imgproc/src/resize.rs
This pull request includes several updates to the `kornia-imgproc` crate, primarily focusing on updating dependencies and refactoring the image resizing code to improve performance and maintainability. The most important changes are listed below:
Dependency updates:
* [`crates/kornia-imgproc/Cargo.toml`](diffhunk://#diff-d446f6d1509e77bfc7093c37b96ae3a3e7390609f73c7ec7b430b9486c47223cL14-R14): Updated the `fast_image_resize` dependency from version `3.0.4` to `5.1.0`.
Code refactoring:
* [`crates/kornia-imgproc/src/resize.rs`](diffhunk://#diff-ce256f3c43d4a27bbe09f39e4ed5d90f82c701a8f60fcc70253ea626a8fb9d8eL7): Removed the `NonZeroU32` import as it is no longer used in the code.
* [`crates/kornia-imgproc/src/resize.rs`](diffhunk://#diff-ce256f3c43d4a27bbe09f39e4ed5d90f82c701a8f60fcc70253ea …
=> Bumpt fast resize

.devcontainer/devcontainer.json, .devcontainer/postCreateCommand.sh, README.md
This pull request introduces a development container (devcontainer) setup for the project. The devcontainer configuration allows developers to have a consistent development environment using Visual Studio Code and Docker.
- **Consistent Development Environment**: Ensures all developers work in the same environment, reducing "it works on my machine" issues.
- **Easy Setup**: Simplifies the setup process for new contributors by providing a pre-configured development environment.
- **Enhanced Tooling**: Includes useful VSCode extensions and tools to improve productivity and code quality.
1. **Devcontainer Configuration**:
- Added devcontainer.json file to define the development container settings.
- The container uses the `mcr.microsoft.com/devcontainers/rust:1-1` image, which includes Rust …
=> feat (devcontainer): setup devcontainer for vscode

crates/kornia-image/src/image.rs, crates/kornia-tensor/src/allocator.rs, crates/kornia-tensor/src/storage.rs, crates/kornia-tensor/src/tensor.rs
This pull request includes several important changes to the `kornia-image` and `kornia-tensor` crates. The changes introduce new methods for creating images and tensors from raw parts, add corresponding tests, and improve memory safety checks in deallocation.
Needed by: https://github.com/copper-project/copper-rs/pull/193/files
New methods for creating images and tensors from raw parts:
* [`crates/kornia-image/src/image.rs`](diffhunk://#diff-d7c919b32e685719baf394dd4faedad8e3f13d3ed905d1ac09cb91ceb3b6618fR172-R197): Added the `from_raw_parts` method to the `Image` struct, which allows creating an image from raw parts. This method includes safety documentation and argument descriptions.
* [`crates/kornia-tensor/src/storage.rs`](diffhunk://#diff-9bceae2c8e26efdd86f447b2f7916b10181a76194b8d74 …
=> create Image and Tensor/Storage from parts

Cargo.toml, crates/kornia-tensor/Cargo.toml, crates/kornia-tensor/src/bincode.rs, crates/kornia-tensor/src/lib.rs, crates/kornia-tensor/src/serde.rs, justfile
This pull request introduces several changes to add support for `bincode` serialization and deserialization to the `kornia-tensor` crate. The changes include updates to dependencies, new module implementations, and additional test cases.
* Added `bincode` as a dependency in `Cargo.toml` and made `serde` and `bincode` optional dependencies in `crates/kornia-tensor/Cargo.toml`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R39) [[2]](diffhunk://#diff-fd43adde823ced4d13b0c4119a4a997b798994f48ab67affb37471fe10cbc6ccL15-R24)
* Implemented `bincode` serialization and deserialization for the `Tensor` struct in `crates/kornia-tensor/src/bincode.rs`.
* Added `bincode` module to `crates/kornia-tensor/src/lib.rs`.
* Added test cases for `bincode` …
=> implement bincode for tensor

crates/kornia-io/src/stream/capture.rs, examples/features/src/main.rs, examples/filters/src/main.rs, examples/rtspcam/src/main.rs, examples/video_write/src/main.rs, examples/webcam/src/main.rs, kornia-viz/src/bin/app.rs
This pull request includes significant refactoring and simplification of the `StreamCapture` implementation in the `kornia-io` crate, as well as minor changes in several example files to remove unnecessary mutability.
Refactoring and simplification of `StreamCapture`:
* Removed the use of `Arc` and `Mutex` for `last_frame` and simplified the `StreamCapture` struct by replacing `last_frame` and `handle` with `appsink` (`crates/kornia-io/src/stream/capture.rs`, [crates/kornia-io/src/stream/capture.rsL1-R8](diffhunk://#diff-54772eec9f4df3e91b9766d5d6e901987ebd59b387782130671c1b1590abcb73L1-R8)).
* Simplified the `start` method by removing the thread handling and using `bus.set_sync_handler` to handle bus messages (`crates/kornia-io/src/stream/capture.rs`, …
=> Simplify stream capture and remove thread

.github/workflows/rust_lint.yml, .github/workflows/rust_test.yml, devel-x86_64.Dockerfile
This pull request includes several updates to the GitHub Actions workflows and a Dockerfile to improve the Rust toolchain installation and usage. The changes simplify the setup process and ensure the use of the latest stable Rust version.
Improvements to GitHub Actions workflows:
* [`.github/workflows/rust_lint.yml`](diffhunk://#diff-28463188e5bcf22600fa82f6d59c8a38cc226e9ca959375b2e40bb6b6940a340L17-R18): Replaced the use of `actions-rs/toolchain` and `actions-rs/cargo` with direct `rustup` and `cargo` commands for installing the Rust toolchain and running `rustfmt` and `clippy`. [[1]](diffhunk://#diff-28463188e5bcf22600fa82f6d59c8a38cc226e9ca959375b2e40bb6b6940a340L17-R18) [[2]](diffhunk://#diff-28463188e5bcf22600fa82f6d59c8a38cc226e9ca959375b2e40bb6b6940a340L47-R42)
* …
=> refactor ci pipelines

README.md
=> Grayscale Example Fixed

crates/kornia-io/Cargo.toml, crates/kornia-io/src/stream/capture.rs, crates/kornia-io/src/stream/error.rs, examples/features/src/main.rs, examples/filters/src/main.rs, examples/rtspcam/src/main.rs, examples/video_write/src/main.rs, examples/webcam/src/main.rs
After discussion: https://discourse.gstreamer.org/t/zero-copy-video-frames/3856/2
This pull request includes several changes to improve the functionality and reliability of the stream capture pipeline in the `kornia-io` crate. The most significant changes involve updating dependencies, introducing a new `FrameBuffer` struct, and modifying the `StreamCapture` implementation to use this new struct. Additionally, there are minor changes to example files to ensure proper mutability of capture objects.
Updates and Dependency Changes:
* Updated `gst` and `gst-app` dependencies to version `0.23.4` in `Cargo.toml`.
Stream Capture Improvements:
* Introduced a new `FrameBuffer` struct to store the frame buffer, width, and height.
* Modified the `StreamCapture` struct to include a `last_frame` …
=> Use Gstreamer Buffer map in StreamCapture

crates/kornia-imgproc/src/core.rs
This pull request includes changes to the `crates/kornia-imgproc/src/core.rs` file to improve the performance and readability of the `std_mean` function by using fixed-size arrays instead of vectors. Additionally, the test code has been updated to reflect these changes.
Changes to `std_mean` function:
* Modified the return type of `std_mean` from `Vec<f64>` to `[f64; 3]` for both standard deviation and mean values.
* Replaced the calculation of `mean` and `variance` from using vectors to using fixed-size arrays for better performance and readability.
Updates to test code:
* Updated the test code to use fixed-size arrays for expected standard deviation and mean values, improving consistency with the updated `std_mean` function.
=> return array in std_mean

crates/kornia-image/src/image.rs, crates/kornia-image/src/ops.rs, crates/kornia-imgproc/src/threshold.rs
This pull request includes several changes to the `Image` struct in the `kornia-image` crate, focusing on improving the API and adding new functionalities. The most important changes include updating the `get_pixel` method, adding a new `set_pixel` method, and renaming test functions to follow a consistent naming convention.
* Updated the `get_pixel` method to return a reference to the pixel value instead of a copy.
* Added a new `set_pixel` method to allow setting the pixel value at given coordinates.
* Updated the documentation for the `get_pixel` method to recommend using the `get` method for better performance.
* Renamed test functions to follow a consistent naming convention by prefixing them with `test_`. [[1]](diffhunk://#diff-d7c919b32e685719baf394dd4faedad8e3f13d3ed905d1ac09cb91ce …
=> image: implement image getter and setter for dev purpose

crates/kornia-imgproc/benches/bench_filters.rs, crates/kornia-imgproc/src/filter/kernels.rs, crates/kornia-imgproc/src/filter/ops.rs, crates/kornia-imgproc/src/filter/separable_filter.rs
solve #168. The algorithm was derived from this [blog post](https://blog.ivank.net/fastest-gaussian-blur.html#results)
=> Implement Box blur fast filter that could approximate gaussian filter

.github/workflows/python_test.yml
It looks like 3.13t CI is blocked on rust-numpy adding free-threaded support. I'll work on that upstream then come back here.
=> add CI for 3.13

Cargo.toml, README.md, crates/kornia-imgproc/src/color/gray.rs, crates/kornia-io/Cargo.toml, crates/kornia-io/benches/bench_io.rs, crates/kornia-io/src/error.rs, crates/kornia-io/src/functional.rs, crates/kornia-io/src/jpegturbo.rs, crates/kornia-io/src/lib.rs, crates/kornia/Cargo.toml, examples/binarize/src/main.rs, examples/color_detector/src/main.rs, examples/hello_world/src/main.rs, examples/histogram/src/main.rs, examples/imgproc/src/main.rs, examples/metrics/src/main.rs, examples/normalize/src/main.rs, examples/normalize_ii/src/main.rs, examples/onnx/src/main.rs, examples/rerun_viz/src/main.rs, examples/rotate/src/main.rs, examples/std_mean/src/main.rs, examples/undistort_image/src/main.rs, justfile, kornia-py/Cargo.toml, kornia-py/justfile, kornia-py/src/io/functional.rs, kornia-py/src/io/jpeg.rs
This pull request includes several changes to the Kornia library, focusing on updating dependencies, renaming functions for clarity, and improving the handling of JPEG images using the turbojpeg library. The most important changes are grouped by theme below.
* Updated the `kornia` dependency version from `v0.1.7` to `v0.1.8` in `Cargo.toml` and `README.md`.
* Updated the `turbojpeg` dependency version from `1.0.0` to `1.2` in `crates/kornia-io/Cargo.toml`.
* Renamed functions to include `_rgb8` suffix for clarity, such as `read_image_any` to `read_image_any_rgb8` and `read_image_jpeg` to `read_image_jpegturbo_rgb8` in `crates/kornia-io/src/functional.rs`. [[1]](diffhunk://#diff-066f8bb7233a0547534d17b285cbcce1bd3600f7f2e059c9dc6464aaa729c3d3L29-R35) …
=> kornia_io: refactor jpegturbo api and specify image types

Cargo.toml, kornia-py/Cargo.toml, scripts/release_rust.sh
This pull request includes updates to the `Cargo.toml` files and a script correction to ensure consistency and correct functionality across the project. The most important changes include updating the version numbers for multiple dependencies and correcting a typo in the release script.
Updates to `Cargo.toml` files:
* Updated category for the `kornia` package to "science::robotics" in `Cargo.toml`.
* Updated version numbers for multiple dependencies from "0.1.9-rc.1" to "0.1.9-rc.2" in `Cargo.toml` and `kornia-py/Cargo.toml`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L23-R34) [[2]](diffhunk://#diff-b578890f0af57d109322f0341862126b0c113a3203c7fbcedf2a7d9bf1308fd2L11-R11)
Script correction:
* Fixed a typo in the `scripts/release_rust.sh` script …
=> chore: bump version to v0.1.9-rc2

crates/kornia-icp/src/icp_vanilla.rs, kornia-py/.gitignore, kornia-py/Cargo.toml, kornia-py/src/icp.rs, kornia-py/src/lib.rs, kornia-py/src/pointcloud.rs, kornia-py/tests/test_icp.py
This pull request introduces several changes to add ICP (Iterative Closest Point) functionality to the `kornia-py` package, including new modules, classes, and tests. The most important changes include adding new dependencies, implementing the ICP algorithm in Rust and exposing it to Python, and creating corresponding unit tests.
* [`kornia-py/Cargo.toml`](diffhunk://#diff-b578890f0af57d109322f0341862126b0c113a3203c7fbcedf2a7d9bf1308fd2R23-R24): Added dependencies for `kornia-icp` and `kornia-3d` crates.
* [`kornia-py/src/icp.rs`](diffhunk://#diff-f644a24f54b90dc5ecdd879826fc028d571e594912b8bfd9d68a89f3b7c9f697R1-R137): Implemented the `PyICPConvergenceCriteria` and `PyICPResult` classes and the `icp_vanilla` function to expose the ICP algorithm to Python.
* …
=> kornia_py: expose icp algorithm to pyo3

crates/kornia-imgproc/benches/bench_color.rs, crates/kornia-imgproc/src/color/gray.rs, crates/kornia-imgproc/src/color/mod.rs, examples/imgproc/src/main.rs
This pull request focuses on enhancing the grayscale image processing functionality in the `kornia-imgproc` crate. The changes include the addition of a new function for converting RGB images to grayscale using `u8` values, the removal of redundant grayscale conversion functions, and updates to benchmarks and examples to utilize the new function.
Key changes:
* Added `gray_from_rgb_u8` function to convert RGB8 images to grayscale using a specific formula.
* Removed redundant grayscale conversion functions (`gray_slice_chunks_pixels`, `gray_slice_chunks_pixels_parallel`, `gray_slice_chunks_rows`, `gray_slice_chunks_rows_parallel`).
* Updated benchmarks in `bench_color.rs` to use the new `gray_from_rgb_u8` function and removed tests for the deleted functions. …
=> color: implement gray from rgb as u8

Cargo.toml, crates/kornia-linalg/Cargo.toml, crates/kornia-linalg/benches/bench_linalg.rs, crates/kornia-linalg/src/lib.rs, crates/kornia-linalg/src/linalg.rs
fixes: #220 
This is a port of : https://github.com/wi-re/tbtSVD/blob/master/source/SVD.h
It calculates V matrix correctly but the remaining S and U matrix are still not accurate.
Correct answer:
Algorithm answer:
`
SVDSet { U: Mat3 { x_axis: Vec3(1.7881393e-7, 0.0, 0.9999999), y_axis: Vec3(0.0, -1.0, 0.0), z_axis: Vec3(0.9999999, 0.0, -1.7881393e-7) }, S: Mat3 { x_axis: Vec3(2.9999995, -0.0, 1.7881393e-7), y_axis: Vec3(0.0, 2.0, -0.0), z_axis: Vec3(-5.364418e-7, 0.0, 0.9999999) }, V: Mat3 { x_axis: Vec3(1.0, 0.0, 0.0), y_axis: Vec3(0.0, 1.0, -0.0), z_axis: Vec3(-0.0, 0.0, 1.0) } }
`
=> Implement SVD for Mat3x3

crates/kornia-tensor-ops/src/ops.rs, crates/kornia-tensor/src/tensor.rs
- `mul_scalar`:- multiplies the tensor by any scalar number
- `powf`:- raises a tensor to a float power
- `min`:- implementation of `torch.minimum` function of pytorch
these functions are used in the implementation of #243, #244
=> Added additional functions for kornia tensors

.github/workflows/python_test.yml, kornia-py/requirements-dev.txt, kornia-py/tests/test_io.py
`pytest-run-parallel` is a tool for converting existing Python test suites into multithreaded stress tests. If there's any use of global state in the implementation of any tested functionality or in any tests, `pytest-run-parallel` usually does a good job of triggering race conditions.
It doesn't replace real multithreaded stress tests of mutable objects but is a good first-pass to shake out any use of global state.
The only test failure was due to use of a thread-unsafe pytest [`tmpdir` fixture](https://docs.pytest.org/en/stable/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures) and I replaced it with direct use of the [`tempfile.TemporaryDirectory` context manager](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory), which is thread-safe.
=> Use pytest-run-parallel in free-threaded CI

crates/kornia-io/src/stream/error.rs
I verified that Rust automatically derives these by looking at the docs for `StreamCaptureError` after applying this PR:
=> Remove unnecessary unsafe Send/Sync impl for StreamCaptureError

crates/kornia-io/Cargo.toml, crates/kornia-io/src/stream/capture.rs, crates/kornia-io/src/stream/error.rs, crates/kornia-io/src/stream/video.rs
This pull request includes several changes to the `crates/kornia-io` package, focusing on updating dependencies and refactoring the `StreamCapture` and `VideoWriter` implementations to use the `circular-buffer` crate and the latest version of the `gstreamer` crate. The most important changes are listed below:
* Updated `gstreamer` and `gstreamer-app` dependencies to version `0.23.5` and added `circular-buffer` as a new dependency in `Cargo.toml`.
* Replaced `gst` and `gst-app` with `gstreamer` and `gstreamer-app` throughout the `StreamCapture` implementation in `capture.rs`. [[1]](diffhunk://#diff-54772eec9f4df3e91b9766d5d6e901987ebd59b387782130671c1b1590abcb73L1-R17) [[2]](diffhunk://#diff-54772eec9f4df3e91b9766d5d6e901987ebd59b387782130671c1b1590abcb73L31-R75)
* Introduced a …
=> io: upgrade gsreamer to 0.23.5 and initialize

crates/kornia-io/Cargo.toml
Fixes #319 
The docs.rs fails to build the documentation because `gstreamer-app-sys` custom build script fails. [See Logs](https://docs.rs/crate/kornia-io/0.1.8/builds/1605403).
After inspecting the [`gstreamer-app-sys/Cargo.toml`](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/main/gstreamer-app/sys/Cargo.toml#L63) and it's [build.rs](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/main/gstreamer-app/sys/build.rs), I came to know that enabling `docsrs` flag would fix the issue. 
Also, `gio-sys` crate also uses `docsrs` flag to disable it's build script
I tested it on my local machine by uninstalling `gstreamer`, and it works.
=> Fix `kornia-io` docs not building on docs.rs

crates/kornia-io/src/functional.rs, crates/kornia-io/src/jpegturbo.rs, kornia-py/src/io/jpeg.rs
Note this is targeted at the PR branch for #334.
Since you're using interior mutability via a `Mutex`, all this `mut` isn't necessary.
=> Python: make encoders and decoders frozen pyclasses

.github/workflows/python_release.yml
Fixes #226 (🚀🧵)
Most of this is fixing bitrot in the Python release automation:
* Works around issues with cmake4 and turbojpeg-sys. I opened https://github.com/honzasp/rust-turbojpeg/issues/30 to track this upstream. Way more complicated than I originally expected because it turns out maturin-action might be running on any one of RHEL 7-9 or Ubuntu!
* Updates to upload-artifact and download-artifact v4, which required updating naming bookkeeping to avoid generating artifacts with duplicate names, which is now banned.
=> Update python release automation, add free-threaded builds

.github/workflows/python_test.yml, .github/workflows/rust_lint.yml, .github/workflows/rust_release.yml, .github/workflows/rust_test.yml
This PR fixes the error thrown by the CI:
```
error: process didn't exit successfully: `sccache /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -vV` (exit status: 2)
--- stderr
sccache: error: Server startup failed: cache storage failed to read: Unexpected (permanent) at read => {"$id":"1","innerException":null,"message":"This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset","typeName":"Microsoft.Azure.DevOps.ArtifactCache.WebApi.ArtifactCacheServiceDecommissionedException, Microsoft.Azure.DevOps.ArtifactCache.WebApi","typeKey":"ArtifactCacheServiceDecommissionedException","errorCode":0,"eventId":3000}
```
=> Fix CI issue with sccache

README.md
In this PR I made the following changes:
- Fixed indentation for some code snippets
- Specify `0.1.9` as crate version instead of `v0.1.9` which is not a correct format
- For the sub-crate section, I replaced their git tag versions with version available on crates.io as that would be same, and IMHO, people would prefer crates.io version. I would revert this, if you think we should mention the git version instead.
=> Fix: README.md - Minor fixes and formatting

kornia-py/Cargo.toml, kornia-py/pyproject.toml
The `include` option in the `kornia-py` `Cargo.toml` file is causing the sdist to miss almost all files.
Also includes trove classifiers.
Fixes the issue pointed out by @zboszor here: https://github.com/kornia/kornia-rs/issues/360#issuecomment-2889989223
=> fix sdist and add trove classifiers

crates/kornia-io/src/conv_utils.rs, crates/kornia-io/src/jpegturbo.rs, crates/kornia-io/src/lib.rs, crates/kornia-io/src/png.rs
This pull request refactors the utility functions for image bit depth conversion by moving them into a dedicated `conv_utils` module, improving code organization and maintainability. Additionally, it updates imports across several files to reflect this change and fixes a minor import path issue for `IoError`.
* Moved utility functions for converting between `Vec<u8>` and `Vec<u16>` (`convert_buf_u8_u16`, `convert_buf_u8_u16_into_slice`, and `convert_buf_u16_u8`) from `lib.rs` to a new `conv_utils` module. This change centralizes these utilities and enhances modularity. (`[[1]](diffhunk://#diff-fe761de759d7a083eac9e0a809ebe8b4de3267a5af96e388ab36bd443f49208eL34-R35)`, `[[2]](diffhunk://#diff-541f4f938469940dba70f6f4e582b682568788b109a04bf776df184a3f46aca8R1-R27)`)
* Updated the `png.rs` …
=> separate internal conv bit functions

crates/kornia-apriltag/benches/bench_decoding.rs, crates/kornia-apriltag/src/decoder.rs, crates/kornia-apriltag/src/lib.rs, crates/kornia-apriltag/src/quad.rs, crates/kornia-image/src/error.rs, crates/kornia-imgproc/benches/bench_features.rs, crates/kornia-imgproc/benches/bench_resize.rs, crates/kornia-imgproc/src/resize.rs, crates/kornia-vlm/src/paligemma/mod.rs, crates/kornia-vlm/src/smolvlm/preprocessor.rs, examples/apriltag/src/main.rs, examples/video_player/src/lib.rs, kornia-py/src/resize.rs
1. NVIDIA Orin
```txt
kornia-apriltag         time:   [11.525 ms 11.526 ms 11.528 ms]
change: [−68.450% −68.443% −68.436%] (p = 0.00 < 0.05)
```
3. AMD Ryzen 7 5800X
```txt
kornia-apriltag         time:   [5.4888 ms 5.4963 ms 5.5049 ms]
change: [−68.551% −68.469% −68.392%] (p = 0.00 < 0.05)
```
=> Add image downscaling support in AprilTag Detection

crates/kornia-apriltag/Cargo.toml, crates/kornia-apriltag/benches/bench_decoding.rs
1. With downscaling factor 2
_`aprilgrid-rs` doesn't support image downscaling yet_ 
```
kornia-apriltag         time:   [12.677 ms 12.680 ms 12.683 ms]
apriltag-c              time:   [7.9444 ms 7.9456 ms 7.9470 ms]
aprilgrid-rs            time:   [12.714 ms 12.716 ms 12.718 ms]
```
2. Without downscaling
```
kornia-apriltag         time:   [46.454 ms 46.460 ms 46.466 ms]
apriltag-c              time:   [26.419 ms 26.425 ms 26.431 ms]
aprilgrid-rs            time:   [12.714 ms 12.716 ms 12.718 ms]
```
=> Add benchmark aprilgrid-rs
